Add query selected statistics method to base resource
C2Devel/pyscaleio pull request #5
Opened 2021-08-23 17:46 UTC by dplyakin

2021-09-22 10:31 UTC, IgorAnohin requested changes
Код - ок.
Нашёл ошибку в `Makefile`.

2021-09-22 10:31 UTC, IgorAnohin commented on Makefile
> +TAG      := $(shell git show-ref --tags -d | grep $(HEAD_SHA) | \
Просто предложения по улучшению:

Я бы вероятно к `grep` добавил `^`, так как мы когда-нибудь можем случано грепнуть что-то из центра чужого хеша. Крайне маловероятно, но как-будто наличие `^` правильнее.

Ещё могу предложить перенести `grep` в `awk`, так как `awk` позволяет фильтровать текст. Что-то вроде `awk '/^$(HEAD_SHA)/ {print $$2}'`

2021-09-22 10:31 UTC, IgorAnohin commented on Makefile
> +		git name-rev --tags --name-only $$(awk '{print $2}'))
`$$(awk '{print $2}'))` работает неправильно.
При наличии тега в переменной `TAG`, он будет записан дважды, вроде `"0.1.7^0 0.1.7^0"`

В текущем варианте, когда мы проверяем `TAG` на пустоту, всё работает, но значение неверное.

`Makefile` съедает первый `$`, поэтому внутри `AWK` раскрывается `$2 -> ""`. Чтобы `TAG` определялся правильно, нужно заменить `print $2` -> `print $$2`

2021-09-28 09:56 UTC, dplyakin commented
Ваще это @Sharpeye90 писал. Андрей, посмотри, пожалуйста.

2021-09-28 10:25 UTC, Sharpeye90 commented on Makefile
> +TAG      := $(shell git show-ref --tags -d | grep $(HEAD_SHA) | \
Да, ты прав ^ совершенно точно будет не лишним. 

Насчет awk вместо grep, тут имхо вкусовщина, так как главная функция TAG показать совпадает ли HEAD с тэжиком или нет. Т.е. я не против, с точки зрения фильтрации текста awk определенно правильное решение. Но мы содержимое TAG нигде не используем. Только наличие содержимого.

2021-09-28 10:25 UTC, Sharpeye90 commented on Makefile
> +		git name-rev --tags --name-only $$(awk '{print $2}'))
Согласен. Срабатывать срабатывает, но лучше сделать правильно.

2021-09-28 12:47 UTC, dplyakin commented on Makefile
> +TAG      := $(shell git show-ref --tags -d | grep $(HEAD_SHA) | \
Таки как вы хотите в итоге? `grep -E ^$(HEAD_SHA)`?

2021-09-28 12:51 UTC, Sharpeye90 commented on Makefile
> +TAG      := $(shell git show-ref --tags -d | grep $(HEAD_SHA) | \
Без -E

2021-09-29 13:55 UTC, IgorAnohin approved these changes

2021-11-15 09:28 UTC, merged